# Generated by Django 3.2.9 on 2021-12-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_auto_20211213_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='following',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='like',
        ),
    ]
