# Generated by Django 3.2.9 on 2021-12-15 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20211215_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='followers',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='like',
            new_name='likes',
        ),
    ]
